### ISSUE TITLE
the num of GPU Registered changed

### ISSUE THREAD

**Issue by tingweiwu** [NVIDIA/k8s-device-plugin#129]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description

the num of GPU Registered first is 8. but after a few days of running, it changed to 4 or 6 .

```
Capacity:
 cpu:                72
 ephemeral-storage:  1146196168Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             525490100Ki
 nvidia.com/gpu:     8
 pods:               110
 rdma/hca:           1k
Allocatable:
 cpu:                71500m
 ephemeral-storage:  1050965677560
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             508028852Ki
 nvidia.com/gpu:     4
 pods:               110
 rdma/hca:           1k

```

no error is displayed in the logs of nvidia-device-plugin 
```
# kubectl logs nvidia-device-plugin-daemonset-h7zzb -n kube-system
2019/07/27 07:33:07 Loading NVML
2019/07/27 07:33:07 Fetching devices.
2019/07/27 07:33:07 Starting FS watcher.
2019/07/27 07:33:07 Starting OS watcher.
2019/07/27 07:33:07 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
2019/07/27 07:33:07 Registered device plugin with Kubelet
```
the version of plugin i use `Image:          nvidia/k8s-device-plugin:1.11`

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host

 - [ ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
 - [ ] The k8s-device-plugin container logs
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
 - [ ] Docker version from `docker version`
 - [ ] Docker command, image and tag used
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by scott-greenberg-sysdig** [comment]
@tingweiwu any chance you'd be willing to attach the information requested in #3? I've been troubleshooting a similar issue and I'm curious if our setups have any commonalities.

**Comment by scott-greenberg-sysdig** [comment]
I was able to reproduce this with the following steps:

1. create a duplicate daemonset of the nvidia-device-plugin daemonset and change name so it doesn’t collide with original daemonset’s namespace
2. apply duplicate daemonset, then delete daemonset.apps/<dupe>
3. wait 30-60min

The gpu count should drop after step 3.

**Comment by scott-greenberg-sysdig** [comment]
I examined the output of journalctl on a on which the GPU count
was zero.  In that log, I observe the following:

```
Nov 13 01:56:55 kube-XXXXX kernel: nvidiafb: HW is currently programmed for CRT^M
Nov 13 01:56:55 kube-XXXXX kernel: nvidiafb: Using CRT on CRTC 0^M
Nov 13 01:56:55 kube-XXXXX kernel: nvidiafb: PCI nVidia NV2 framebuffer (4MB @ 0x5F000000000)^M
Nov 13 01:56:55 kube-XXXXX kernel: NVRM: The NVIDIA probe routine was not called for 4 device(s).^M
Nov 13 01:56:55 kube-XXXXX kernel: NVRM: This can occur when a driver such as: ^M
NVRM: nouveau, rivafb, nvidiafb or rivatv ^M
NVRM: was loaded and obtained ownership of the NVIDIA device(s).^M
Nov 13 01:56:55 kube-XXXXX kernel: NVRM: Try unloading the conflicting kernel module (and/or^M
NVRM: reconfigure your kernel without the conflicting^M
NVRM: driver(s)), then try loading the NVIDIA kernel module^M
NVRM: again.^M
Nov 13 01:56:55 kube-XXXXX kernel: NVRM: No NVIDIA devices probed.^M
```

This shows that first the nvidiafb driver is loaded and is registered to drive
the GPUs, and that second the nvidia driver tries to register to drive the GPUs
and fails to do so because nvidiafb is already registered.  (The resulting
error message explicitly says that the failure can be caused by the presence
of nvidiafb.)

As a result, the nvidia-driver pod, which tried to load the
nvidia driver, fails and does not create the /dev/nvidia* character device
files.The nvidia plugin that supplies kubelet with the count of the available GPUs
counts the /dev/nvidia[0-9]* character device files.  Since the nvidia-driver
pod failed to load the module and did not create the device files, there are
no /dev/nvidia[0-9] device files, so the plugin reports 0 GPUs to kubelet.

This problem seems to be a race between something triggering the automatic loading
of modules and the nvidia-driver pod.  blacklisting the nvidiafb driver should fix this issue.

**Comment by RenaudWasTaken** [comment]
Thanks for debugging this and letting us know!

@tingweiwu in your case this is likely due to error being detected by the device plugin.
It is currently pretty stringent on error detection and offlining the GPUs. This can be reset by restarting the device plugin or setting the `DP_DISABLE_HEALTHCHECKS` environment variable in the container
