### ISSUE TITLE
Release 1.0.0-beta6 missing from https://github.com/NVIDIA/k8s-device-plugin/releases

### ISSUE THREAD

**Issue by herb-kuta-lge** [NVIDIA/k8s-device-plugin#173]
https://github.com/NVIDIA/k8s-device-plugin/releases has 1.0.0-beta5 marked as _Latest release_, but `README.md` mentions 1.0.0-beta6.

Also https://github.com/NVIDIA/k8s-device-plugin#changelog doesn't have an entry for 1.0.0-beta5.

**Comment by klueska** [comment]
That's strange because I am the one that pushed out the `beta5` release, and what is now marked as the `beta6` release in the changelog is the changelog I wrote for `beta5` (as seen here: https://github.com/NVIDIA/k8s-device-plugin/tree/1.0.0-beta5#version-100-beta5).  

It seems when the beta6 release was done, that some mistakes were made with updating the changelog and the releases page. I'll see what I can do about fixing this.
