### ISSUE TITLE
With volume-mounts strategy, pod shouldn't fail when no permission to read NVIDIA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by zhsj** [NVIDIA/k8s-device-plugin#203]
If a non privileged pod is not allocating any GPU with nividia.com/gpu, but still using an image from ngc(which set NVIDIA_VISIBLE_DEVICES regardless), the pod will fail to create.

error: insufficient privileges to read device list from NVIDIA_VISIBLE_DEVICES envvar

So in pod spec, we still need to override the NVIDIA_VISIBLE_DEVICES envvar. However it seems to break the design principle for volume-mounts strategy, which wants to achieve `k8s-device-plugin is the only mechanism by which pods are able to gain access to a GPU.`

Steps to reproduce:

Same as [Testing in kubernetes -> 2)](https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit#heading=h.tec6pygavof).

**Comment by klueska** [comment]
At present, what you are seeing is expected behaviour. What would you expect to happen differently? Launch the container, but silently *not* give it any GPUs?

**Comment by zhsj** [comment]
I expect to create a pod successfully regardless of the image, only using `nividia.com/gpu` to controll the num of GPU, without knowing the NVIDIA_VISIBLE_DEVICES env.

But today I need to know whether the image has NVIDIA_VISIBLE_DEVICES env. Or I need to unset NVIDIA_VISIBLE_DEVICES if I don't want GPU when using ngc image.

**Comment by klueska** [comment]
If you actually ask for some `nvidia.com/gpu` resources, then it doesn't matter if the image has `NVIDIA_VISIBLE_DEVICES` set or not -- it will be ignored, and the volume-mounts set up by the plugin will be used instead.

It's only a problem in the case where you attempt to launch an NGC container (which has `NVIDIA_VISIBLE_DEVICES` set by default), but you *don't* request any `nvidia.com/gpu` resources (so the plugin is never invoked and no volume mounts are set up / `NVIDIA_VISIBLE_DEVICES` is not overwritten by the plugin). In this case you will get the error you are seeing because the system thinks you are trying to request GPUs via the envvar, but don't have the correct permissions to do so.

The only way to address the issue you are seeing would be to change the underlying `nvidia-container-toolkit` to silently ignore `NVIDIA_VISIBLE_DEVICES` if a container does not have the proper permissions to use it to control which GPUs get injected. There is no way to do this from the plugin because it does not get invoked in the case where no `nvidia.com/gpu` resources are requested. 

I agree this is a bit unintutive, but I'm not 100% sure what the right semantics should be at the moment.
At the very least we should print a warning in the nvidi-container-toolkit log if this occurs, but maybe it makes sense to not error out as it's doing today.

Let me think  about this a bit more and I'll report back here on what we can.

**Comment by hoangtnm** [comment]
Hi @klueska, I read your [Preventing unprivileged access to GPUs
in Kubernetes](https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit#heading=h.tec6pygavof) document. I tried to follow step 3 in Section **Configuring the k8s-device-plugin**, which indicates the following settings:

```bash
helm install \
  --version=0.7.0-rc.7 \
  --generate-name \
  --set securityContext.privileged=true \
  --set deviceListStrategy=volume-mounts \
  nvdp/nvidia-device-plugin
```

I think your guide was updated in Sep 2020, which is two years ago I guess. Therefore, I tried to follow those steps in the latest version of [k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin/tree/v0.12.3#configuring-the-nvidia-device-plugin-binary), however, I don't see the option `securityContext.privileged=true` in the [Configuring the NVIDIA device plugin binary](https://github.com/NVIDIA/k8s-device-plugin/tree/v0.12.3#configuring-the-nvidia-device-plugin-binary). Therefore, I wonder whether the `--set securityContext.privileged=true` is still necessary or not?
