### ISSUE TITLE
Cannot create device plugin pod

### ISSUE THREAD

**Issue by inductor** [NVIDIA/k8s-device-plugin#216]
### 1. Issue or feature description

Cannot create device plugin daemonset because 0.7.2 has not released on Docker Hub
```
  Warning  Failed     8s (x2 over 23s)   kubelet            Failed to pull image "nvidia/k8s-device-plugin:v0.7.2": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/nvidia/k8s-device-plugin:v0.7.2": failed to resolve reference "docker.io/nvidia/k8s-device-plugin:v0.7.2": docker.io/nvidia/k8s-device-plugin:v0.7.2: not found
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host
 - [ ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
 - [ ] The k8s-device-plugin container logs
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
 - [ ] Docker version from `docker version`
 - [ ] Docker command, image and tag used
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by klueska** [comment]
Yes. Sorry, this is a known issue at the moment.

We pushed the changes to the README and the static yaml files / helm chart to master  just before triggering the 0.7.2 release in our CI/CD pipeline. Unfortunately, the release pipeline failed, preventing the release artifacts from being published.

We should have this fixed early next week. Until then, please continue to use v0.7.1 instead of v0.7.2.
