### ISSUE TITLE
v0.7.2 yaml not avilable as referenced in the documentation

### ISSUE THREAD

**Issue by psarossy** [NVIDIA/k8s-device-plugin#217]
The [device plugin setup guidelines](https://github.com/NVIDIA/k8s-device-plugin#enabling-gpu-support-in-kubernetes) reference https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.7.2/nvidia-device-plugin.yml but this file does not exist.

**Comment by klueska** [comment]
https://github.com/NVIDIA/k8s-device-plugin/issues/216#issuecomment-743795310

Yes. Sorry, this is a known issue at the moment.

We pushed the changes to the README and the static yaml files / helm chart to master just before triggering the 0.7.2 release in our CI/CD pipeline. Unfortunately, the release pipeline failed, preventing the release artifacts from being published.

We should have this fixed early next week. Until then, please continue to use v0.7.1 instead of v0.7.2.
