### ISSUE TITLE
Is it better to change the docker runtime from nvidia to the default runC？

### ISSUE THREAD

**Issue by pineking** [NVIDIA/k8s-device-plugin#27]
In the current settings, the nvidia runtime is set to the default docker runtime instead of the origin runC.
so an issue as described in https://github.com/kubernetes/kubernetes/issues/59631 https://github.com/kubernetes/kubernetes/issues/59629
All GPUs are exposed into the container.

so one way of the solution is to use env to tell nvidia-container-runtime not to expose the GPUs.
another better way:
1. set the default docker runtime back to runC.
2. we do not need nvidia-container-runtime to do pre-start hooks, use k8s-device-plugin to do the same jobs, such as inject GPU device.

so the issue https://github.com/kubernetes/kubernetes/issues/59631 can be fixed. 

@flx42 @RenaudWasTaken @cmluciano @jiayingz @vikaschoudhary16

**Comment by flx42** [comment]
This behavior is an unfortunate limitation of the current API. As we already discussed to the K8s work group, we need our hook to enable GPU support.

If you use CRI-O, you can also add custom hooks and then you don't need the runc replacement. I think @RenaudWasTaken will document that soon, he's been testing this path.

**Comment by RenaudWasTaken** [comment]
Hello @pineking !

> so one way of the solution is to use env to tell nvidia-container-runtime not to expose the GPUs.
another better way:

That doesn't really work as the device plugin isn't called on every container, just containers requesting at least one GPU.

To give some additional context on the use of nvidia-container-runtime, it allows multiple things:
- We have one unique library that is used for for all the runtimes (instead of one implementation for Kubernetes, one for docker, ...)
- The library will try to fix common driver installation issues
- GKE's GPU device plugin uses that method and doesn't support our Graphical images (Vulkan, OpenGL, ...)
- The device plugin API is still completely insufficient to support new features as we add them in (MPI, MPS, ...)

**Comment by pineking** [comment]
>That doesn't really work as the device plugin isn't called on every container, just containers requesting at least one GPU.

As you said, it does's work to set the env via device plugin when there is no GPU request or `request == 0`. 
I also file a PR https://github.com/kubernetes/kubernetes/pull/59698 to solve this, make the device plugin can be called by the device manager when `limit == 0`, but the PR is closed since that's not a good solution.
