### ISSUE TITLE
I deploy k8s 1.10 and deploy the k8s-device-plugin but the Capacity of GPU not found 

### ISSUE THREAD

**Issue by kinglion811** [NVIDIA/k8s-device-plugin#43]
I deploy the k8s v1.10,and deploy k8s-device-plugin v1.10,but when I use 
$kubectl describe node bjpg-g271.yz02
can not find the capatity of GPU

I deploy cuda is 
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

nvidia-docker is 17.03.2
I can run the GPU container by docker run,but the GPU can not scheduler by k8s

**Comment by pineking** [comment]
@kinglion811 do you set the nvidia runtime as the default docker runtime?

**Comment by RenaudWasTaken** [comment]
@kinglion811 can you provide:
- [ ] The output of nvidia-smi -a on your GPU node (from the host)
- [ ]  Your docker configuration file on your GPU node (e.g: /etc/docker/daemon.json)
- [ ]  The k8s-device-plugin container logs (kubectl logs -n kubesystem TheDevicePluginPod

Thanks!

**Comment by ray1888** [comment]
i have the same issue 
1. nvidia-smi 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:05:00.0 Off |                  N/A |
| 27%   40C    P8    12W / 180W |      0MiB /  8118MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:06:00.0 Off |                  N/A |
| 27%   36C    P8     7W / 180W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 00000000:09:00.0 Off |                  N/A |
| 27%   27C    P8     7W / 180W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

2. docker daemon.json
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "registry-mirrors": [ "https://registry.docker-cn.com","https://hub.docker.com"],
    "insecure-registries": [ "172.17.195.73:5000"]
}

because it can't schedule to the node , always pending , so i don't have the log

**Comment by RenaudWasTaken** [comment]
Hello @ray1888 !

Can you paste the logs of the device plugin?

Thanks!

**Comment by RenaudWasTaken** [comment]
Closing as no further answers were provided.
