### ISSUE TITLE
Unable to install in Ubuntu 20.04 a nvidia container toolkit with version < 1.14.4

### ISSUE THREAD

**Issue by AlexisGitHu** [NVIDIA/k8s-device-plugin#509]
Today I was trying to deploy with nvidia-device-plugin for kubernetes with a rtx 3070 ti. I upgraded my CUDA drivers to 545 and my cuda version to 12.3. 

However, an error triggers and indicates that the version of Cuda drivers is insufficient with the cuda runtime (provided by installing the nvidia-ctk), whose version is 1.14.4.

I guess that by downgrading the container toolkit version will be enough to solve the issue, but the official nvidia links (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/1.13.1/install-guide.html#install-guide ) install the last version and there is no way to install others.

**Comment by elezar** [comment]
From the device plugin logs, it is clear that the GPUs are not being injected into the device plugin container. (Note the "could not load NVML library" message.

Could you provide more information on how Kubernetes is deployed? My current hypothesis is that K8s is using containerd as a container engine and that the NVIDIA Container Runtime has not been configured in the containerd config.

Assuming the default containerd config is used, you should be able to run (as highlighted in our [docs](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-containerd-for-kubernetes)):
```
sudo nvidia-ctk runtime configure --runtime=containerd --set-as-default --dry-run
```
to confirm that the config is loaded and the specifics to the NVIDIA Container Runtime can be applied.

With this done you can apply the config changes required by running:
```
sudo nvidia-ctk runtime configure --runtime=containerd --set-as-default
sudo systemctl restart containerd
```

Note that if you don't want to set the `nvidia` runtime as default, you can also leave off the `--set-as-default` flag and use a runtime class to launch GPU jobs.

Note that a restart of the device plugin is required here.

One thing that is still strange is that you're able to actually launch a GPU job at all, since the device plugin should *not* be reporting any `nvidia.com/gpu` resources if none can be found.

**Comment by AlexisGitHu** [comment]
It was all solved using cri-dockerd as the container runtime for the kubernetes cluster. I thought that as Docker used containerd, it will be transparent to use the GPU with kubernetes with that runtime as long as Docker was configured in such a way, but it seems it is not.

Once the container runtime was changed, it detected the GPU and the pod task was launched succesfully on gpu.

I guess this closes the issue.
