### ISSUE TITLE
”nvidia-container-cli: initialization error: cuda error: unknown error“ on CPU node

### ISSUE THREAD

**Issue by pineking** [NVIDIA/k8s-device-plugin#52]
on k8s CPU node, set nvidia as the default runtime,
```
{
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "default-runtime": "nvidia",
    "registry-mirrors": ["https://registry.docker-cn.com"]
}
```
when we start the pod of `nvidia/k8s-device-plugin:1.10`
the error is:
```
kubelet, 00-25-90-c0-f7-c8  Error: failed to start container "nvidia-device-plugin-ctr": Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --utility --pid=3567 /var/lib/docker/overlay2/c4498cb4052e704adff6d4ce5d4a8190afb89764a7bc8645d97c6b0520ba3a81/merged]\\\\nnvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\""
  Warning  BackOff                1s (x3 over 5s)    kubelet, 00-25-90-c0-f7-c8  Back-off restarting failed container
```

what we expected:
`nvidia/k8s-device-plugin:1.10` can run on non-GPU node with nvidia docker runtime.

**Comment by flx42** [comment]
You shouldn't install `nvidia-container-runtime` on CPU nodes. It won't work because our runtime needs to use CUDA/NVML.
You can either use a `nodeSelector` on the daemonset to avoid scheduling to these CPU nodes, or you can let the device plugin starts on every node, but don't install the NVIDIA runtime, our device plugin will just wait indefinitely:
https://github.com/NVIDIA/k8s-device-plugin/blob/v1.10/main.go#L23

**Comment by pineking** [comment]
Thanks for your detailed explanation.
 I will set the runtime to the default runc.
