### ISSUE TITLE
Setting nvidia.com/gpu:NoSchedule taint causes GPU nodes to repel k8s-device-plugin, making GPU nodes unschedulable for GPU jobs

### ISSUE THREAD

**Issue by notnami** [NVIDIA/k8s-device-plugin#68]
**The original issue described below shows a symptom, but not the cause of the problem. For the underlying cause, please see further comments.**

Hi everyone,

I'm sure this will be something obvious in retrospect, but I've been stuck with this for a while.

As the title says, my GPU node is reporting itself as having `alpha.kubernetes.io/nvidia-gpu` instead of `nvidia.com/gpu`, where previously it had reported `nvidia.com/gpu`. As a result, my pods, which request `nvidia.com/gpu` don't get scheduled.

Here is the relevant section of `kubectl describe node`:

```
Capacity:
 alpha.kubernetes.io/nvidia-gpu:  1
 cpu:                             4
 ephemeral-storage:               130046416Ki
 hugepages-1Gi:                   0
 hugepages-2Mi:                   0
 memory:                          62879988Ki
 pods:                            110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:  1
 cpu:                             4
 ephemeral-storage:               119850776788
 hugepages-1Gi:                   0
 hugepages-2Mi:                   0
 memory:                          62777588Ki
 pods:                            110
System Info:
 Machine ID:                 6b08f5e8c7ae4843a46ae7f889a4078a
 System UUID:                EC292D81-8715-3D89-A766-3E173EAC5036
 Boot ID:                    3ed3f5ec-1ddf-43b4-9235-bf8fe261a9d3
 Kernel Version:             4.4.0-1065-aws
 OS Image:                   Ubuntu 16.04.5 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://17.3.2
 Kubelet Version:            v1.10.7
 Kube-Proxy Version:         v1.10.7
```

I had the GPU nodes working earlier. I am lost as to what exactly changed, but before this stopped working, I added a Taint so that pods that don't need a GPU would not get scheduled on this node.

For context, I am running the cluster with `kops` on AWS. I am using k8s-device-plugin v1.10. I know the recommended version of k8s and the plug-in is 1.11, but I know it has worked before with earlier versions, so I expect it should work with 1.10

I have tried re-setting the node afresh, but to no avail. I have also upgraded my cluster's k8s version to 1.10 from 1.9, but also to no result. Any help would be appreciated!

**Comment by notnami** [comment]
I removed the Taint, and the `nvidia.com/gpu` showed up. It seems the Taint was repelling the `k8s-device-plugin` pod from running on the node. Short of manually editing the deployment file for `k8s-device-plugin`, would anyone have suggestions for setting up a Taint that would both repel non-GPU pods and allow the `k8s-device-plugin` to run on a GPU node?

**Comment by flx42** [comment]
Take a look at this article:
https://notes.mindprince.in/2017/12/17/dedicated-node-pools-and-ExtendedResourceToleration-admission-controller.html
This will create automatic tolerations based on `nvidia.com/gpu`.

**Comment by notnami** [comment]
Thanks for the link @flx42. Unforunately, the `ExtendedResourceToleration` admission was the exact thing I used to set up the Taint, which caused my GPU node to repel `k8s-device-plugin`. Have you been able to use that admission controller successfully with the device plugin?

**Comment by flx42** [comment]
`ExtendedResourceToleration` add tolerations, not taints. You added the `taint` yourself, right?

**Comment by mindprince** [comment]
@flx42 Your device plugin needs to tolerate `nvidia.com/gpu` taint so that it can work with `ExtendedResourceToleration`. (Anything which doesn't request GPUs but still need to run on GPU nodes need to tolerate user-added taints)

We made GKE's device plugin tolerate everything (since it's such a critical addon): https://github.com/kubernetes/kubernetes/blob/v1.11.2/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml#L28

**Comment by flx42** [comment]
@mindprince wait, but does that means the administrator set the `nvidia.com/gpu` taint before deploying the device plugin?

**Comment by flx42** [comment]
Hm, or I guess that would also happen if the administrator used a `NoExecute` taint, that would evict the device plugin afterwards, right? Is `NoSchedule` insufficient?

**Comment by mindprince** [comment]
We set a `nvidia.com/gpu:NoSchedule` taint while setting up a GPU node pool. So, that nothing gets scheduled on the node. Then device-plugin and driver installer which tolerates all taints run on the node. Similarly kube-proxy, and other critical addons that tolerate all taints run on the node.

Then any GPU pod that requests GPUs can run on the node because the admission controller will tolerate that taint for those pods.

**Comment by flx42** [comment]
It doesn't harm to add tolerations, but it feels like what you describe is backward. Do you mean you have a special case for GPU nodes when provisioning an instance? I would like to reach a point where GPU nodes are auto-detected, and each container is deployed in the right order automatically: driver container -> device plugin -> monitoring stack. I've started writing some thoughts about this here:
https://docs.google.com/document/d/16FPbc7qtqvJNPlk2sBlYOyhIB9DYXvaUQrEPP4bHmxI/edit?usp=sharing

The device plugin should be the one setting up the `taint` after it has successfully started. An alternative implementation of our device plugin might expose `nvidia.com/vgpu` instead.
With a `NoSchedule` taint it would open the door to CPU jobs starting on this node in parallel with the device plugin initialization. In this case we could use a **different** taint than the extended resource one, for instance a taint that would set by `node-feature-discovery`, before the device driver is even added.

But there is also the question of whether we should be opinionated about this. If we decide to unconditionally taint the node in the device plugin, we are opinionated since we will repel CPU nodes and require the deployment of the ExtendedResourceToleration admission controller.
@jeremyeder mentioned they would prefer to use priorities and preemption instead, you would be able to run CPU jobs if there are no GPU jobs pending.

**Comment by flx42** [comment]
Anyway, I'm getting a bit off-topic and I'm not sure @notnami cares about all this. But the gist is that I don't feel it's a solved problem, and while that's true I don't want to force users to label/taint their nodes (but the toleration should be harmless as I said, we could add it).
