### ISSUE TITLE
When does k8s device plugin  support k8s’s  new version ，v1.12 or v1.13?

### ISSUE THREAD

**Issue by Chaos-Ju** [NVIDIA/k8s-device-plugin#78]
When does k8s device plugin  support k8s’s  new version ，v1.12 or v1.13?

**Comment by RenaudWasTaken** [comment]
Hello!

The device plugin already supports the latests k8s versions! Because the API it uses is beta, we have backwards compatibility and can use the v1.11 plugin in v1.12 and v1.13!

We'll probably publish a v1.12 that improves some things (logging, registration, ...) but shouldn't have any user facing impact.

I'll add a table in the readme as soon as I have some time to clarify this :)
